- name: variables
  hosts: local
  connection: local
  tasks:
  - name: print the variable
    ansible.builtin.debug:
      msg: "Course is {{ COURSES }}, Duration is {{ DURATIONTime }}, Trainer is {{ TRAINERS }}"